### PR TITLE
Speakers Tab UI - implementation

### PR DESCRIPTION
**Pull request by ChandanKhamitkar**
### Speakers

**Preveiw - 1**
Screenshot 2024-12-17 223134

**Preveiw - 2**
Screenshot 2024-12-17 223141

### Volunteers
image

### CODE REVIEW

**Comment by ChandanKhamitkar** [comment]
Spacing between Speakers Card will fixed soon.

**Comment by ChandanKhamitkar** [comment]
- Fixed the spacing issues between Speakers cards.
- Added **Volunteers Tab*

**Comment by ChandanKhamitkar** [comment]
@ManasMalla I've tried to replace the verified icon on different place, review it, screen shot is attached above.

**Comment by ManasMalla** [comment]
@ChandanKhamitkar It looks good. LGTM; However, make sure the tagline for every speaker comes to 1 row, increase the width of each speaker element wider and verify the sizes of the text in the speaker item.

**Comment by ManasMalla** [comment]
@ManasMalla I'll fix up on the anti-aliasing of text and font-weight issues

**Pull request merged**
